server:
    port: 8761
spring:
    application:
        name: sc-eureka-server
    security:
        user:
            name: user
            password: 123456

eureka:
    client:
        # 表示是否将自己注册到 Eureka Server ，默认为 true。
        # 由于当前应用就是 Eureka Server，故而设为false。
        register-with-eureka: false
        # 表示是否从Eureka Server 获取注册信息，默认为 true 。
        # 因为这是一个单点的 Eureka Server ，不需要同步其他的 Eureka Server 节点
        # 的数据，故而设为 false 。
        fetch-registry: false
        service-url:
            # 设置与Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址。
            # 默认是 http://localhost:8761/eureka.client， 多个地址间可使用,分隔。
            defaultZone: http://user:123456@localhost:8761/eureka/
